// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Lottery$Type } from "./Lottery";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Lottery"]: Lottery$Type;
    ["contracts/Lottery.sol:Lottery"]: Lottery$Type;
  }
}
