// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { LotteryToken$Type } from "./LotteryToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LotteryToken"]: LotteryToken$Type;
    ["contracts/LotteryToken.sol:LotteryToken"]: LotteryToken$Type;
  }
}
